services:
  - type: web
    name: projectjarvis1
    runtime: python
    region: oregon
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:10000
