services:
  - type: web
    name: jarvis-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:10000 main:app"
    envVars:
      - key: PORT
        value: 10000
 